// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clustermessage.proto

package clustermessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandType int32

const (
	CommandType_Reserved        CommandType = 0
	CommandType_ClusterRegist   CommandType = 1
	CommandType_ClusterUnregist CommandType = 2
	CommandType_NeighborRoute   CommandType = 3
	CommandType_SubTreeRoute    CommandType = 4
	CommandType_DeployReq       CommandType = 5
	CommandType_DeployResp      CommandType = 6
	CommandType_ControlReq      CommandType = 7
	CommandType_ControlResp     CommandType = 8
	CommandType_EdgeReport      CommandType = 9
)

var CommandType_name = map[int32]string{
	0: "Reserved",
	1: "ClusterRegist",
	2: "ClusterUnregist",
	3: "NeighborRoute",
	4: "SubTreeRoute",
	5: "DeployReq",
	6: "DeployResp",
	7: "ControlReq",
	8: "ControlResp",
	9: "EdgeReport",
}

var CommandType_value = map[string]int32{
	"Reserved":        0,
	"ClusterRegist":   1,
	"ClusterUnregist": 2,
	"NeighborRoute":   3,
	"SubTreeRoute":    4,
	"DeployReq":       5,
	"DeployResp":      6,
	"ControlReq":      7,
	"ControlResp":     8,
	"EdgeReport":      9,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}

func (CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb5c8b0b58767cdb, []int{0}
}

// ClusterMessage is the message between cluster controllers and maybe cc and cluster shim.
type ClusterMessage struct {
	Head                 *MessageHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Body                 string       `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClusterMessage) Reset()         { *m = ClusterMessage{} }
func (m *ClusterMessage) String() string { return proto.CompactTextString(m) }
func (*ClusterMessage) ProtoMessage()    {}
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb5c8b0b58767cdb, []int{0}
}

func (m *ClusterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterMessage.Unmarshal(m, b)
}
func (m *ClusterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterMessage.Marshal(b, m, deterministic)
}
func (m *ClusterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMessage.Merge(m, src)
}
func (m *ClusterMessage) XXX_Size() int {
	return xxx_messageInfo_ClusterMessage.Size(m)
}
func (m *ClusterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMessage proto.InternalMessageInfo

func (m *ClusterMessage) GetHead() *MessageHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ClusterMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type MessageHead struct {
	// MessageID is the uuid of a cluster message.
	// if the message comes from a crd, the messageid is the name of the crd.
	MessageID            string      `protobuf:"bytes,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Command              CommandType `protobuf:"varint,2,opt,name=Command,proto3,enum=clustermessage.CommandType" json:"Command,omitempty"`
	CluterSelector       string      `protobuf:"bytes,3,opt,name=CluterSelector,proto3" json:"CluterSelector,omitempty"`
	ClusterName          string      `protobuf:"bytes,4,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	ParentClusterName    string      `protobuf:"bytes,5,opt,name=ParentClusterName,proto3" json:"ParentClusterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MessageHead) Reset()         { *m = MessageHead{} }
func (m *MessageHead) String() string { return proto.CompactTextString(m) }
func (*MessageHead) ProtoMessage()    {}
func (*MessageHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb5c8b0b58767cdb, []int{1}
}

func (m *MessageHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHead.Unmarshal(m, b)
}
func (m *MessageHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHead.Marshal(b, m, deterministic)
}
func (m *MessageHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHead.Merge(m, src)
}
func (m *MessageHead) XXX_Size() int {
	return xxx_messageInfo_MessageHead.Size(m)
}
func (m *MessageHead) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHead.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHead proto.InternalMessageInfo

func (m *MessageHead) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *MessageHead) GetCommand() CommandType {
	if m != nil {
		return m.Command
	}
	return CommandType_Reserved
}

func (m *MessageHead) GetCluterSelector() string {
	if m != nil {
		return m.CluterSelector
	}
	return ""
}

func (m *MessageHead) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *MessageHead) GetParentClusterName() string {
	if m != nil {
		return m.ParentClusterName
	}
	return ""
}

type ControllerTask struct {
	Destination          string   `protobuf:"bytes,1,opt,name=Destination,proto3" json:"Destination,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	URI                  string   `protobuf:"bytes,3,opt,name=URI,proto3" json:"URI,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerTask) Reset()         { *m = ControllerTask{} }
func (m *ControllerTask) String() string { return proto.CompactTextString(m) }
func (*ControllerTask) ProtoMessage()    {}
func (*ControllerTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb5c8b0b58767cdb, []int{2}
}

func (m *ControllerTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerTask.Unmarshal(m, b)
}
func (m *ControllerTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerTask.Marshal(b, m, deterministic)
}
func (m *ControllerTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerTask.Merge(m, src)
}
func (m *ControllerTask) XXX_Size() int {
	return xxx_messageInfo_ControllerTask.Size(m)
}
func (m *ControllerTask) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerTask.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerTask proto.InternalMessageInfo

func (m *ControllerTask) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *ControllerTask) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ControllerTask) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *ControllerTask) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ControllerTaskResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerTaskResponse) Reset()         { *m = ControllerTaskResponse{} }
func (m *ControllerTaskResponse) String() string { return proto.CompactTextString(m) }
func (*ControllerTaskResponse) ProtoMessage()    {}
func (*ControllerTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb5c8b0b58767cdb, []int{3}
}

func (m *ControllerTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerTaskResponse.Unmarshal(m, b)
}
func (m *ControllerTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerTaskResponse.Marshal(b, m, deterministic)
}
func (m *ControllerTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerTaskResponse.Merge(m, src)
}
func (m *ControllerTaskResponse) XXX_Size() int {
	return xxx_messageInfo_ControllerTaskResponse.Size(m)
}
func (m *ControllerTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerTaskResponse proto.InternalMessageInfo

func (m *ControllerTaskResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ControllerTaskResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ControllerTaskResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type DeployTask struct {
	Replicas             int32             `protobuf:"varint,1,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	PodParams            map[string]string `protobuf:"bytes,2,rep,name=PodParams,proto3" json:"PodParams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status               string            `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeployTask) Reset()         { *m = DeployTask{} }
func (m *DeployTask) String() string { return proto.CompactTextString(m) }
func (*DeployTask) ProtoMessage()    {}
func (*DeployTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb5c8b0b58767cdb, []int{4}
}

func (m *DeployTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployTask.Unmarshal(m, b)
}
func (m *DeployTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployTask.Marshal(b, m, deterministic)
}
func (m *DeployTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployTask.Merge(m, src)
}
func (m *DeployTask) XXX_Size() int {
	return xxx_messageInfo_DeployTask.Size(m)
}
func (m *DeployTask) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployTask.DiscardUnknown(m)
}

var xxx_messageInfo_DeployTask proto.InternalMessageInfo

func (m *DeployTask) GetReplicas() int32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *DeployTask) GetPodParams() map[string]string {
	if m != nil {
		return m.PodParams
	}
	return nil
}

func (m *DeployTask) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterEnum("clustermessage.CommandType", CommandType_name, CommandType_value)
	proto.RegisterType((*ClusterMessage)(nil), "clustermessage.ClusterMessage")
	proto.RegisterType((*MessageHead)(nil), "clustermessage.MessageHead")
	proto.RegisterType((*ControllerTask)(nil), "clustermessage.ControllerTask")
	proto.RegisterType((*ControllerTaskResponse)(nil), "clustermessage.ControllerTaskResponse")
	proto.RegisterType((*DeployTask)(nil), "clustermessage.DeployTask")
	proto.RegisterMapType((map[string]string)(nil), "clustermessage.DeployTask.PodParamsEntry")
}

func init() { proto.RegisterFile("clustermessage.proto", fileDescriptor_cb5c8b0b58767cdb) }

var fileDescriptor_cb5c8b0b58767cdb = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0x4d, 0xbb, 0x2d, 0xb7, 0x5b, 0x96, 0x5d, 0xa6, 0xa9, 0x1a, 0x08, 0x55, 0x7d, 0x40,
	0x05, 0xa1, 0x22, 0x0d, 0x21, 0x21, 0xc4, 0x13, 0xed, 0x04, 0x7b, 0xd8, 0x54, 0xb9, 0xed, 0x07,
	0xb8, 0xcd, 0x55, 0x17, 0x96, 0xc4, 0xc1, 0x76, 0x26, 0xe5, 0xcf, 0xf8, 0x03, 0xfe, 0x81, 0xaf,
	0x41, 0x76, 0xbc, 0x36, 0xed, 0xde, 0x7c, 0x8e, 0x8f, 0xef, 0xb9, 0xf7, 0xdc, 0x04, 0xce, 0x57,
	0x69, 0xa9, 0x34, 0xc9, 0x8c, 0x94, 0xe2, 0x6b, 0x1a, 0x15, 0x52, 0x68, 0x81, 0xe1, 0x2e, 0x3b,
	0x58, 0x40, 0x38, 0xae, 0x99, 0xdb, 0x9a, 0xc1, 0x8f, 0xd0, 0xfe, 0x49, 0x3c, 0xee, 0x79, 0x7d,
	0x6f, 0xd8, 0xbd, 0x7a, 0x35, 0xda, 0x2b, 0xe3, 0x64, 0x46, 0xc2, 0xac, 0x10, 0x11, 0xda, 0xdf,
	0x45, 0x5c, 0xf5, 0x5a, 0x7d, 0x6f, 0x18, 0x30, 0x7b, 0x1e, 0xfc, 0xf3, 0xa0, 0xdb, 0x50, 0xe2,
	0x6b, 0x08, 0x1c, 0xbc, 0x99, 0xd8, 0xca, 0x01, 0xdb, 0x12, 0xf8, 0x19, 0x0e, 0xc7, 0x22, 0xcb,
	0x78, 0x1e, 0xdb, 0x22, 0xe1, 0x73, 0x57, 0x77, 0x3d, 0xaf, 0x0a, 0x62, 0x4f, 0x5a, 0x7c, 0x6b,
	0x7b, 0xd7, 0x24, 0x67, 0x94, 0xd2, 0x4a, 0x0b, 0xd9, 0xf3, 0x6d, 0xe5, 0x3d, 0x16, 0xfb, 0xd0,
	0x75, 0x33, 0xde, 0xf1, 0x8c, 0x7a, 0x6d, 0x2b, 0x6a, 0x52, 0xf8, 0x01, 0xce, 0xa6, 0x5c, 0x52,
	0xae, 0x9b, 0xba, 0x8e, 0xd5, 0x3d, 0xbf, 0x18, 0x14, 0x10, 0x8e, 0x45, 0xae, 0xa5, 0x48, 0x53,
	0x92, 0x73, 0xae, 0x1e, 0x8c, 0xc3, 0x84, 0x94, 0x4e, 0x72, 0xae, 0x13, 0x91, 0xbb, 0x01, 0x9b,
	0x14, 0x5e, 0xc0, 0xc1, 0x2d, 0xe9, 0x7b, 0x11, 0xbb, 0x98, 0x1c, 0xc2, 0x08, 0xfc, 0x05, 0xbb,
	0x71, 0x8d, 0x9b, 0xe3, 0x26, 0xce, 0x76, 0x23, 0xce, 0x5f, 0x70, 0xb1, 0xeb, 0xc8, 0x48, 0x15,
	0x22, 0x57, 0x64, 0x82, 0x9d, 0x27, 0x19, 0x29, 0xcd, 0xb3, 0xc2, 0xfa, 0xfa, 0x6c, 0x4b, 0xe0,
	0x1b, 0x80, 0x99, 0xe6, 0xba, 0x54, 0x63, 0x11, 0x93, 0x75, 0xee, 0xb0, 0x06, 0xb3, 0xf1, 0xf2,
	0x1b, 0x5e, 0x7f, 0x3d, 0x80, 0x09, 0x15, 0xa9, 0xa8, 0xec, 0x68, 0x97, 0x70, 0xc4, 0xa8, 0x48,
	0x93, 0x15, 0x57, 0xb6, 0x7e, 0x87, 0x6d, 0x30, 0xfe, 0x80, 0x60, 0x2a, 0xe2, 0x29, 0x97, 0x3c,
	0x53, 0xbd, 0x56, 0xdf, 0x1f, 0x76, 0xaf, 0xde, 0xed, 0x6f, 0x6e, 0x5b, 0x6a, 0xb4, 0xd1, 0x5e,
	0xe7, 0x5a, 0x56, 0x6c, 0xfb, 0xd6, 0xa4, 0x53, 0x77, 0xe5, 0x3a, 0x71, 0xe8, 0xf2, 0x1b, 0x84,
	0xbb, 0x8f, 0x4c, 0x5e, 0x0f, 0x54, 0xb9, 0x84, 0xcd, 0x11, 0xcf, 0xa1, 0xf3, 0xc8, 0xd3, 0x92,
	0x5c, 0xb0, 0x35, 0xf8, 0xda, 0xfa, 0xe2, 0xbd, 0xff, 0xe3, 0x41, 0xb7, 0xf1, 0xe1, 0xe0, 0xb1,
	0x19, 0x45, 0x91, 0x7c, 0xa4, 0x38, 0x7a, 0x81, 0x67, 0x70, 0xe2, 0x96, 0xca, 0x68, 0x9d, 0x28,
	0x1d, 0x79, 0xf8, 0x12, 0x4e, 0x1d, 0xb5, 0xc8, 0x65, 0x4d, 0xb6, 0x8c, 0xee, 0x8e, 0x92, 0xf5,
	0xfd, 0x52, 0x48, 0x26, 0x4a, 0x4d, 0x91, 0x8f, 0x11, 0x1c, 0xcf, 0xca, 0xe5, 0x5c, 0x12, 0xd5,
	0x4c, 0x1b, 0x4f, 0x20, 0xa8, 0x07, 0x65, 0xf4, 0x3b, 0xea, 0x60, 0xf8, 0x14, 0xa1, 0xd9, 0x53,
	0x74, 0x60, 0xb0, 0xdb, 0x9f, 0xb9, 0x3f, 0xc4, 0x53, 0xd3, 0x98, 0xc3, 0xaa, 0x88, 0x8e, 0x8c,
	0xe0, 0x3a, 0x5e, 0x13, 0xa3, 0x42, 0x48, 0x1d, 0x05, 0xcb, 0x03, 0xfb, 0xb7, 0x7e, 0xfa, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0x15, 0xfc, 0xa7, 0xa6, 0xc5, 0x03, 0x00, 0x00,
}
